### model
model_name_or_path: wheeler404/qwen2-tiny
reward_model: saves/outputs/medical_gpt_simple/qwen2.5_rm_dpozh
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: full
lora_rank: 8
lora_target: all
infer_backend: vllm

### dataset
dataset_dir: saves/data
dataset: medical_sft_1K_format
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/outputs/medical_gpt_simple/qwen2.5_ppo_medical
logging_steps: 10
log_level: error
log_level_replica: error
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
